doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4

    orm:
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    Car:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Car'
                        prefix: 'App\Car'
                        alias: Car
                    Moto:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Moto'
                        prefix: 'App\Moto'
                        alias: Moto
                    Product:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Product'
                        prefix: 'App\Product'
                        alias: Product
