doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4

    orm:
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    Products:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Products'
                        prefix: 'App\Products'
                        alias: Products
